language: node_js
node_js:
- '6'
before_script:
- npm install
script:
- npm test
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
- scripts/deploy.sh
env:
  global:
  - secure: mqeRUD7ryRU1fo8VLVa8VZDWP0MFyB0bjZ2naly8KbkHgRIu+o+m5ruvW4wdLr/I9bCWj13YtF244TrahekiYOAEzHo4j9232EpeXhQ6m+53DubcFYg6yairAnzxJ9A2YoUunnjEaf8LIigKY9eCDHUyHkgaUT8nnbVTt1CUPCra1luqGtYKiSABNc9We+incVtqdqUGRpUKb479k9krneW8qn2bRz1hgpvd6aHriO4Anj6E1ON8eBHi+tXCRliX3RZs7xWrtS5cwyYL+I4b6JQw5hHxH9h/iogG41ID0NO7SpWQ9cF09SI5bJrQAbH3Jy8YqJxQRow2kpxKOpkz/KmWIhh6OlIz1Ele8o8A4mgjuX4Ny+fye2JIY2zt08DpXS8wi357Q3vKM1pW1pHeoCIkNdc60zvFi81DdLR4hf1qU9ywcV8yxKSTHAIuKQ150GHrQeLioCMcaVaVEAZOFPBq6ne9CLMM034n0KhbiWkZjdXB4TlCxSVtxv5rPskr5d4dmWUOOSVqZ72D75MVWtAPDHdHzgpjoo9tNbWAPZi8aUa47Vqhyxtb5bUPkj7aglUEzEgr9tvYjAqA4okf7XPLl81YUMh/rPDOf1vyGZNjZLi8/kHcn4aJYlYo6jYfdXVlYo9nKB6yp5ZxQgF4J66miAK6xaQacFzfCtetYkU=
  - secure: q71lJdq8z1mepvSad+7quqcfbUfI0w+SudqAG7I1OYlS+GsHLKYxxihrhLVmezi3RVLutb4Nv7Gxq/52LNx3gQOLxsUEfMbvYTyhZ0gHIqz+/rS4sU/RpSVavXuOD8jwv5sS7Khu9xSChKCqhh0dRiwClcBmi0OwogkcMyULDbC17vV440OWYZ572nRUECIJD0OY1Ag6B4xF1z6B2GNzlLHO5Fr8rMtMJRFJH+dNZ+paOFCgv+RX9wihYRX89WnJxBPUZjfbvbKyecaxxwH5t/+sOa6+XqVlarZ/ndJ6D6pzhfO+A+KlleOEBJ5pNf1o4A90XrV6LnlgCBguA1bW8bdTvKgQyEpOU6Kh6IeMoRgM3wNCUWR9zG+4UPbhX2lPG1iPHFmZbBkNrAg/uhe27tRO9Et3psTSfOEkXS52kycBeHOf+hAL4youPjnsDhaI/jRPSFGMtRTMag+s6G1Qp03XHUEbX9RLjxMdE4iq/53LomNR5rgKdaGGMKnze6L9UVxNOmlYRyM9Gm3PPSM6BJv41N/ABmsLjAKHh+f/hW+d51UhvdFp9xA8SQxvbJhSfGUK/EYk/P/Bc4jiJYxDiMEKDyJ6nV5b01RtWeUA/cSxRHKzRDblTw5PThB4I7lqM6bTcBhmV8SeUnTCfOTQLhxesbBTp6875Csh1zSr+24=
